server:
  port: 8000

spring:
  application:
    name: event-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
    register-with-eureka: true
    fetch-registry: true